name: spendwise_trakcer
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Responsive UI
  flutter_screenutil: ^5.9.3

  # Firebase & Authentication
  firebase_core: ^3.15.2
  firebase_auth: ^5.4.0
  cloud_firestore: ^5.6.0
  intl: ^0.20.2

  # Provider (state management)
  provider: ^6.1.2

  # Export
  csv: ^6.0.0
  excel: ^3.0.0

  # File sharing (mobile) + temp directory
  share_plus: ^10.0.0
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/app_icon.png
    - assets/images/profile.png

# This must stay at the very edge (no spaces)
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#031511"
  adaptive_icon_foreground: "assets/images/app_icon.png"